### ISSUE TITLE
小程序登录报错

### ISSUE THREAD

**Issue by zhixinfang** [no1xuan/photo#2]
GET https://域名/user/login?code=0a1qgC000Ggw8T1vXP000egA8t4qgC0r 500(env: Windows,mp,1.06.2407120; lib: 3.6.3)
success @ index.js? [sm]:16

**Comment by no1xuan** [comment]
你可以与我联系，远程帮你看下

**Comment by no1xuan** [comment]
请重新拉取前后端代码，现已更新登录失败会把错误原因打印到微信开发者工具的控制台
