### ISSUE TITLE
预览版高清版后台数据库都是设置的免费下载，但是点击下载没反应，没不给报错

### ISSUE THREAD

**Issue by zhixinfang** [no1xuan/photo#3]
预览版高清版后台数据库都是设置的免费下载，但是点击下载没反应，没不给报错

**Comment by no1xuan** [comment]
> 预览版高清版后台数据库都是设置的免费下载，但是点击下载没反应，没不给报错

如果是开发者工具没反应，那么需要我远程协助帮你查看，如果是体验版或者线上版那么是安全域名没有添加

**Comment by zhixinfang** [comment]
> > 预览版高清版后台数据库都是设置的免费下载，但是点击下载没反应，没不给报错
> 
> 如果是开发者工具没反应，那么需要我远程协助帮你查看，如果是体验版或者线上版那么是安全域名没有添加

我电脑上测试了，下载的是html，所以保存不下来

**Comment by no1xuan** [comment]
> > > 预览版高清版后台数据库都是设置的免费下载，但是点击下载没反应，没不给报错
> > 
> > 
> > 如果是开发者工具没反应，那么需要我远程协助帮你查看，如果是体验版或者线上版那么是安全域名没有添加
> 
> 我电脑上测试了，下载的是html，所以保存不下来

yml里面的图片存储服务器没配置正确就会导致下载出现html

**Comment by zhixinfang** [comment]
> > > > 预览版高清版后台数据库都是设置的免费下载，但是点击下载没反应，没不给报错
> > > 
> > > 
> > > 如果是开发者工具没反应，那么需要我远程协助帮你查看，如果是体验版或者线上版那么是安全域名没有添加
> > 
> > 
> > 我电脑上测试了，下载的是html，所以保存不下来
> 
> yml里面的图片存储服务器没配置正确就会导致下载出现html

但是我上传的照片都已经存到pic文件夹了，

**Comment by no1xuan** [comment]
> > > > > 预览版高清版后台数据库都是设置的免费下载，但是点击下载没反应，没不给报错
> > > > 
> > > > 
> > > > 如果是开发者工具没反应，那么需要我远程协助帮你查看，如果是体验版或者线上版那么是安全域名没有添加
> > > 
> > > 
> > > 我电脑上测试了，下载的是html，所以保存不下来
> > 
> > 
> > yml里面的图片存储服务器没配置正确就会导致下载出现html
> 
> 但是我上传的照片都已经存到pic文件夹了，

你是本地调试的吧，需要借助nginx才行，可以下一个phpstudy里面安装nginx，然后创建一个网站，将目录绑定到你的图片存储文件夹，然后把yml里面的ip换成你电脑ip，端口换成这个网站的端口
