### ISSUE TITLE
小程序制作中以后就提示系统繁忙，请稍后再试

### ISSUE THREAD

**Issue by wmxerni** [no1xuan/photo#4]
更新到最新的2024.12.17版本后(前后端、数据库都已更新),制作证件照的时候，可以登陆，美颜也可以开，但是一上传制作以后，就提示系统繁忙，请稍后再试。

**Comment by no1xuan** [comment]
好了，原因：API接口服务器死机了，刚重启

**Comment by wmxerni** [comment]
有关网站、公众号内的问题请前往；1、微信小程序：爱折腾的医学生，在小程序内的文章留言；2、前往
    
        https://mznzd.com
    
    ，登录网站，通过网站给我们评论留言；此邮箱不回复有关网站及公众号内相关的消息，有关工作及生活上的邮件，在看到邮件后，会第一时间给您回复，谢谢。
